// ==========================================
// FUN EMOJIS
// ==========================================
const funEmojis = [
    "🎨", "🚀", "🌟", "🎈", "🍎", "🦖", "🚗", "🧸", "⚽", "🧩", "🥁", "🌈", "🦋", "🍄", "🍉",
    "🦁", "🐯", "🐘", "🦒", "🦓", "🐵", "🐼", "🐻", "🦊", "🐱", "🐶", "🐰", "🐭", "🐸", "🐢",
    "🐳", "🐬", "🐙", "🦀", "🐠", "🐡", "🐚", "🐮", "🐷", "🐑", "🐴", "🐔", "🐤", "🐣", "🦆",
    "🐞", "🐝", "🐌", "🐜", "🦗", "🍦", "🍩", "🍪", "🍕", "🍔", "🍟", "🌮", "🧁", "🍭", "🍫",
    "🍓", "🍍", "🍇", "🍋", "🥑", "🥞", "🥨", "🧀", "🌭", "🍿", "🍰", "🥦", "🌽", "🍒", "🌻",
    "🌹", "🌵", "🌲", "🌴", "🍀", "☘️", "🌿", "🎋", "🌙", "☀️", "☁️", "❄️", "🌊", "🌋", "🪐",
    "🌠", "🛰️", "🛸", "👾", "🤖", "🦄", "🐉", "🧜‍♀️", "🧚", "🧞", "🧙", "🏰", "👑", "💎", "🪄",
    "🏀", "🏈", "⚾", "🎾", "🏐", "🎱", "🎳", "⛳", "🛹", "🚴", "🏆", "🎸", "🎹", "🎻", "🎺",
    "🎷", "📸", "🎮", "🎲", "🪀", "🪁", "🪆", "🎒", "🖍️", "🖌️", "🔭", "🧲", "📚", "🎬", "🎡",
    "🎢", "⛲", "🚜", "🚲", "🛴", "🛶", "⛵", "🚁", "🚂", "🚑", "🚒", "🚓", "🚕", "🚌"
];

// ==========================================
// REWARD DATA
// ==========================================
const rewardData = [
    ["🐶", "Keep Going! 🐾"], ["🐱", "Keep Going! 🐟"], ["🐿️", "Keep Going! 🌰"],
    ["🌻", "Keep Going! ☀️"], ["🍔", "Keep Going! 🍟"], ["🤖", "Keep Going! ⚙️"],
    ["🦄", "Keep Going! ✨"], ["🦁", "Roaring Success! 🦁"], ["🐯", "Grrr-eat Job! 🐯"],
    ["🐘", "Ton of Fun! 🐘"], ["🦒", "Reaching High! 🦒"], ["🦓", "Spot On! 🦓"],
    ["🐵", "Monkeying Around! 🐵"], ["🐼", "Panda-stic! 🐼"], ["🐻", "Bear-y Good! 🐻"],
    ["🦊", "Clever Fox! 🦊"], ["🐰", "Hopping High! 🐰"], ["🐭", "Mighty Mouse! 🐭"],
    ["🐸", "Un-frog-ettable! 🐸"], ["🐢", "Steady Wins! 🐢"], ["🍕", "Slice of Win! 🍕"],
    ["🍔", "Well Done! 🍔"], ["🍟", "Fry-nomenal! 🍟"], ["🌮", "Taco-bout Great! 🌮"],
    ["🍩", "Donut Stop! 🍩"], ["🍪", "Tough Cookie! 🍪"], ["🍦", "Cool Move! 🍦"],
    ["🍎", "Appley-ever After! 🍎"], ["🍓", "Berry Bright! 🍓"], ["🍍", "Pine-apple King! 🍍"],
    ["🥑", "Bravocado! 🥑"], ["🥦", "Super Veggie! 🥦"], ["🌽", "A-maize-ing! 🌽"],
    ["🍒", "Cherry on Top! 🍒"], ["🧁", "Sweet Victory! 🧁"], ["🌲", "Branching Out! 🌲"],
    ["🌵", "Sharp Work! 🌵"], ["🌹", "Bloomed Bright! 🌹"], ["🌈", "Color Me Proud! 🌈"],
    ["☀️", "Sunny Day! ☀️"], ["🌙", "Moonshot! 🌙"], ["⛰️", "Peak Power! ⛰️"],
    ["🌊", "Making Waves! 🌊"], ["❄️", "Ice Cold Skill! ❄️"], ["🍃", "Fresh Start! 🍃"],
    ["🍄", "Magic Growth! 🍄"], ["🐚", "Shell-shocking! 🐚"], ["☘️", "Lucky Charm! ☘️"],
    ["🍁", "Falling for Win! 🍁"], ["🚀", "Blast Off! 🚀"], ["🛸", "Out of This World! 🛸"],
    ["🌠", "Star Power! 🌠"], ["🪐", "Planet Pro! 🪐"], ["☄️", "Fast as Comet! ☄️"],
    ["🌍", "World Class! 🌍"], ["🛰️", "In Orbit! 🛰️"], ["🧑‍🚀", "Space Explorer! 🧑‍🚀"],
    ["🌌", "Galactic Genius! 🌌"], ["🔭", "Visionary! 🔭"], ["🌞", "Solar Flare! 🌞"],
    ["🌕", "Full Moon! 🌕"], ["✨", "Sparkle On! ✨"], ["👾", "Space Invader! 👾"],
    ["📡", "Deep Space Ace! 📡"], ["🪄", "Magic Touch! 🪄"], ["🏰", "Kingdom Hero! 🏰"],
    ["🧚", "Fairy Dust! 🧚"], ["🧜", "Mermaid Magic! 🧜"], ["🧙", "Wizardly Wise! 🧙"],
    ["💎", "Rare Gem! 💎"], ["⚔️", "Brave Knight! ⚔️"], ["🛡️", "Shield Up! 🛡️"],
    ["🏺", "Ancient Myth! 🏺"], ["🗝️", "Key to Success! 🗝️"], ["🕯️", "Glow Getter! 🕯️"],
    ["📜", "Epic Tale! 📜"], ["👑", "Royal Win! 👑"], ["⚽", "Goal Getter! ⚽"],
    ["🏀", "Nothing But Net! 🏀"], ["🏈", "Touchdown! 🏈"], ["⚾", "Home Run! ⚾"],
    ["🎾", "Court King! 🎾"], ["🏐", "Spike It! 🏐"], ["🏉", "Scored Big! 🏉"],
    ["🎱", "On the Ball! 🎱"], ["🎳", "Strike! 🎳"], ["⛳", "Hole in One! ⛳"],
    ["🥋", "Black Belt! 🥋"], ["🥊", "Knockout! 🥊"], ["🛹", "Skater Pro! 🛹"],
    ["🚴", "Pedal Power! 🚴"], ["🏆", "Champion! 🏆"], ["🎨", "Masterpiece! 🎨"],
    ["📸", "Snapshot! 📸"], ["🎸", "Rock On! 🎸"], ["🎹", "Key Player! 🎹"],
    ["🧶", "Yarn Spinner! 🧶"], ["🎮", "Game On! 🎮"], ["🎲", "Lucky Roll! 🎲"],
    ["🧩", "Perfect Fit! 🧩"], ["📚", "Book Worm! 📚"], ["🎬", "Direct Hit! 🎬"]
];

// ==========================================
// MASTER DICTIONARY LIST
// ==========================================
const dictionaryList = [
    // 🟢 PHASE 1: SINGLE WORDS (264 Words)
    { english: "Look", hindi: "देखो", hinglish: "Dekho", phase: 1 },
    { english: "Listen", hindi: "सुनो", hinglish: "Suno", phase: 1 },
    { english: "Come", hindi: "आओ", hinglish: "Aao", phase: 1 },
    { english: "Go", hindi: "जाओ", hinglish: "Jao", phase: 1 },
    { english: "Stop", hindi: "रुको", hinglish: "Ruko", phase: 1 },
    { english: "Run", hindi: "भागो", hinglish: "Bhago", phase: 1 },
    { english: "Jump", hindi: "कूदो", hinglish: "Kudo", phase: 1 },
    { english: "Sit", hindi: "बैठो", hinglish: "Baitho", phase: 1 },
    { english: "Stand", hindi: "खड़े हो", hinglish: "Khade ho", phase: 1 },
    { english: "Eat", hindi: "खाओ", hinglish: "Khao", phase: 1 },
    { english: "Drink", hindi: "पियो", hinglish: "Piyo", phase: 1 },
    { english: "Sleep", hindi: "सो जाओ", hinglish: "So jao", phase: 1 },
    { english: "Wake up", hindi: "उठो", hinglish: "Utho", phase: 1 },
    { english: "Play", hindi: "खेलो", hinglish: "Khelo", phase: 1 },
    { english: "Give", hindi: "दो", hinglish: "Do", phase: 1 },
    { english: "Take", hindi: "लो", hinglish: "Lo", phase: 1 },
    { english: "Catch", hindi: "पकड़ो", hinglish: "Pakdo", phase: 1 },
    { english: "Throw", hindi: "फेंको", hinglish: "Fainko", phase: 1 },
    { english: "Wash", hindi: "धो लो", hinglish: "Dho lo", phase: 1 },
    { english: "Open", hindi: "खोलो", hinglish: "Kholo", phase: 1 },
    { english: "Close", hindi: "बंद करो", hinglish: "Band karo", phase: 1 },
    { english: "Tell", hindi: "बताओ", hinglish: "Batao", phase: 1 },
    { english: "Ask", hindi: "पूछो", hinglish: "Pucho", phase: 1 },
    { english: "Smile", hindi: "मुस्कुराओ", hinglish: "Muskurao", phase: 1 },
    { english: "Wait", hindi: "इंतज़ार", hinglish: "Intezaar", phase: 1 },
    { english: "Read", hindi: "पढ़ो", hinglish: "Padho", phase: 1 },
    { english: "Write", hindi: "लिखो", hinglish: "Likho", phase: 1 },
    { english: "Hide", hindi: "छुपो", hinglish: "Chupo", phase: 1 },
    { english: "Find", hindi: "ढूंढो", hinglish: "Dhoondo", phase: 1 },
    { english: "Walk", hindi: "चलो", hinglish: "Chalo", phase: 1 },
    { english: "Laugh", hindi: "हंसो", hinglish: "Hanso", phase: 1 },
    { english: "Cry", hindi: "रोओ", hinglish: "Roo", phase: 1 },
    { english: "Push", hindi: "धक्का दो", hinglish: "Dhakka do", phase: 1 },
    { english: "Pull", hindi: "खींचो", hinglish: "Kheencho", phase: 1 },
    { english: "Drop", hindi: "गिरा दो", hinglish: "Gira do", phase: 1 },
    { english: "Bring", hindi: "लाओ", hinglish: "Lao", phase: 1 },
    { english: "Make", hindi: "बनाओ", hinglish: "Banao", phase: 1 },
    { english: "Break", hindi: "तोड़ो", hinglish: "Todo", phase: 1 },
    { english: "Clean", hindi: "साफ़ करो", hinglish: "Saaf karo", phase: 1 },
    { english: "Show", hindi: "दिखाओ", hinglish: "Dikhao", phase: 1 },
    { english: "Learn", hindi: "सीखो", hinglish: "Seekho", phase: 1 },
    { english: "Talk", hindi: "बात करो", hinglish: "Baat karo", phase: 1 },
    { english: "Think", hindi: "सोचो", hinglish: "Socho", phase: 1 },
    { english: "Wear", hindi: "पहनो", hinglish: "Pehno", phase: 1 },
    { english: "Hit", hindi: "मारो", hinglish: "Maaro", phase: 1 },
    { english: "Buy", hindi: "खरीदो", hinglish: "Khareedo", phase: 1 },
    { english: "Sell", hindi: "बेचो", hinglish: "Becho", phase: 1 },
    { english: "Win", hindi: "जीतो", hinglish: "Jeeto", phase: 1 },
    { english: "Lose", hindi: "हारो", hinglish: "Haaro", phase: 1 },
    { english: "Build", hindi: "बनाओ", hinglish: "Banao", phase: 1 },
    { english: "Tear", hindi: "फाड़ो", hinglish: "Faado", phase: 1 },
    { english: "Cut", hindi: "काटो", hinglish: "Kaato", phase: 1 },
    { english: "Paste", hindi: "चिपकाओ", hinglish: "Chipkao", phase: 1 },
    { english: "Draw", hindi: "चित्र बनाओ", hinglish: "Chitra banao", phase: 1 },
    { english: "Fill color", hindi: "रंग भरो", hinglish: "Rang bharo", phase: 1 },
    { english: "Water", hindi: "पानी", hinglish: "Paani", phase: 1 },
    { english: "Food", hindi: "खाना", hinglish: "Khana", phase: 1 },
    { english: "Milk", hindi: "दूध", hinglish: "Doodh", phase: 1 },
    { english: "Clothes", hindi: "कपड़े", hinglish: "Kapde", phase: 1 },
    { english: "Shoes", hindi: "जूते", hinglish: "Joote", phase: 1 },
    { english: "Toy", hindi: "खिलौना", hinglish: "Khilona", phase: 1 },
    { english: "Book", hindi: "किताब", hinglish: "Kitaab", phase: 1 },
    { english: "Bed", hindi: "बिस्तर", hinglish: "Bistar", phase: 1 },
    { english: "Door", hindi: "दरवाज़ा", hinglish: "Darwaza", phase: 1 },
    { english: "Window", hindi: "खिड़की", hinglish: "Khidki", phase: 1 },
    { english: "Fan", hindi: "पंखे", hinglish: "Pankha", phase: 1 },
    { english: "Car", hindi: "गाड़ी", hinglish: "Gaadi", phase: 1 },
    { english: "House", hindi: "घर", hinglish: "Ghar", phase: 1 },
    { english: "Friend", hindi: "दोस्त", hinglish: "Dost", phase: 1 },
    { english: "Sun", hindi: "सूरज", hinglish: "Suraj", phase: 1 },
    { english: "Rain", hindi: "बारिश", hinglish: "Baarish", phase: 1 },
    { english: "Hand", hindi: "हाथ", hinglish: "Haath", phase: 1 },
    { english: "Eyes", hindi: "आंखें", hinglish: "Aankhein", phase: 1 },
    { english: "Hair", hindi: "बाल", hinglish: "Baal", phase: 1 },
    { english: "Soap", hindi: "साबुन", hinglish: "Sabun", phase: 1 },
    { english: "Box", hindi: "डिब्बा", hinglish: "Dabba", phase: 1 },
    { english: "Color", hindi: "रंग", hinglish: "Rang", phase: 1 },
    { english: "Paper", hindi: "कागज़", hinglish: "Kagaz", phase: 1 },
    { english: "Bag", hindi: "बस्ता", hinglish: "Basta", phase: 1 },
    { english: "Trash", hindi: "कचरा", hinglish: "Kachra", phase: 1 },
    { english: "Chair", hindi: "कुर्सी", hinglish: "Kursi", phase: 1 },
    { english: "Table", hindi: "मेज़", hinglish: "Mez", phase: 1 },
    { english: "Plate", hindi: "थाली", hinglish: "Thali", phase: 1 },
    { english: "Spoon", hindi: "चम्मच", hinglish: "Chammach", phase: 1 },
    { english: "Bottle", hindi: "बोतल", hinglish: "Botal", phase: 1 },
    { english: "Phone", hindi: "फ़ोन", hinglish: "Phone", phase: 1 },
    { english: "TV", hindi: "टीवी", hinglish: "TV", phase: 1 },
    { english: "Boy", hindi: "लड़का", hinglish: "Ladka", phase: 1 },
    { english: "Girl", hindi: "लड़की", hinglish: "Ladki", phase: 1 },
    { english: "Mother", hindi: "मम्मी", hinglish: "Mummy", phase: 1 },
    { english: "Father", hindi: "पापा", hinglish: "Papa", phase: 1 },
    { english: "Brother", hindi: "भाई", hinglish: "Bhai", phase: 1 },
    { english: "Sister", hindi: "बहन", hinglish: "Behen", phase: 1 },
    { english: "Head", hindi: "सर", hinglish: "Sar", phase: 1 },
    { english: "Leg", hindi: "पैर", hinglish: "Paer", phase: 1 },
    { english: "Apple", hindi: "सेब", hinglish: "Seb", phase: 1 },
    { english: "Banana", hindi: "केला", hinglish: "Kela", phase: 1 },
    { english: "Potato", hindi: "आलू", hinglish: "Aloo", phase: 1 },
    { english: "Onion", hindi: "प्याज़", hinglish: "Pyaaz", phase: 1 },
    { english: "Sugar", hindi: "शक्कर", hinglish: "Shakar", phase: 1 },
    { english: "Salt", hindi: "नमक", hinglish: "Namak", phase: 1 },
    { english: "Rice", hindi: "चावल", hinglish: "Chawal", phase: 1 },
    { english: "Bread", hindi: "रोटी", hinglish: "Roti", phase: 1 },
    { english: "Biscuit", hindi: "बिस्कुट", hinglish: "Biskut", phase: 1 },
    { english: "Juice", hindi: "रस", hinglish: "Ras", phase: 1 },
    { english: "Knife", hindi: "चाकू", hinglish: "Chaku", phase: 1 },
    { english: "Fork", hindi: "कांटा", hinglish: "Kaanta", phase: 1 },
    { english: "Bowl", hindi: "कटोरी", hinglish: "Katori", phase: 1 },
    { english: "Ball", hindi: "गेंद", hinglish: "Gend", phase: 1 },
    { english: "Bat", hindi: "बल्ला", hinglish: "Balla", phase: 1 },
    { english: "Tree", hindi: "पेड़", hinglish: "Ped", phase: 1 },
    { english: "Flower", hindi: "फूल", hinglish: "Phool", phase: 1 },
    { english: "Grass", hindi: "घास", hinglish: "Ghaas", phase: 1 },
    { english: "Bird", hindi: "चिड़िया", hinglish: "Chidiya", phase: 1 },
    { english: "Animal", hindi: "जानवर", hinglish: "Janwar", phase: 1 },
    { english: "Dog", hindi: "कुत्ता", hinglish: "Kutta", phase: 1 },
    { english: "Cat", hindi: "बिल्ली", hinglish: "Billi", phase: 1 },
    { english: "Game", hindi: "खेल", hinglish: "Khel", phase: 1 },
    { english: "Remote", hindi: "रिमोट", hinglish: "Remote", phase: 1 },
    { english: "Screen", hindi: "स्क्रीन", hinglish: "Screen", phase: 1 },
    { english: "Video", hindi: "वीडियो", hinglish: "Video", phase: 1 },
    { english: "Song", hindi: "गाना", hinglish: "Gaana", phase: 1 },
    { english: "Dance", hindi: "नाच", hinglish: "Naach", phase: 1 },
    { english: "Face", hindi: "चेहरा", hinglish: "Chehra", phase: 1 },
    { english: "Nose", hindi: "नाक", hinglish: "Naak", phase: 1 },
    { english: "Mouth", hindi: "मुंह", hinglish: "Munh", phase: 1 },
    { english: "Ear", hindi: "कान", hinglish: "Kaan", phase: 1 },
    { english: "Teeth", hindi: "दांत", hinglish: "Daant", phase: 1 },
    { english: "Stomach", hindi: "पेट", hinglish: "Pet", phase: 1 },
    { english: "Back", hindi: "पीठ", hinglish: "Peeth", phase: 1 },
    { english: "Pain", hindi: "दर्द", hinglish: "Dard", phase: 1 },
    { english: "Medicine", hindi: "दवा", hinglish: "Dawa", phase: 1 },
    { english: "School", hindi: "स्कूल", hinglish: "School", phase: 1 },
    { english: "Teacher", hindi: "टीचर", hinglish: "Teacher", phase: 1 },
    { english: "Pen", hindi: "कलम", hinglish: "Kalam", phase: 1 },
    { english: "Pencil", hindi: "पेंसिल", hinglish: "Pencil", phase: 1 },
    { english: "Story", hindi: "कहानी", hinglish: "Kahani", phase: 1 },
    { english: "Picture", hindi: "चित्र", hinglish: "Chitra", phase: 1 },
    { english: "Music", hindi: "संगीत", hinglish: "Sangeet", phase: 1 },
    { english: "Clock", hindi: "घड़ी", hinglish: "Ghadi", phase: 1 },
    { english: "Time", hindi: "समय", hinglish: "Samay", phase: 1 },
    { english: "Moon", hindi: "चांद", hinglish: "Chaand", phase: 1 },
    { english: "Star", hindi: "तारा", hinglish: "Tara", phase: 1 },
    { english: "Sky", hindi: "आसमान", hinglish: "Aasmaan", phase: 1 },
    { english: "Earth", hindi: "ज़मीन", hinglish: "Zameen", phase: 1 },
    { english: "Fire", hindi: "आग", hinglish: "Aag", phase: 1 },
    { english: "Wind", hindi: "हवा", hinglish: "Hawa", phase: 1 },
    { english: "Road", hindi: "सड़क", hinglish: "Sadak", phase: 1 },
    { english: "Shop", hindi: "दुकान", hinglish: "Dukaan", phase: 1 },
    { english: "Money", hindi: "पैसे", hinglish: "Paise", phase: 1 },
    { english: "Computer", hindi: "कंप्यूटर", hinglish: "Computer", phase: 1 },
    { english: "Charger", hindi: "चार्जर", hinglish: "Charger", phase: 1 },
    { english: "Battery", hindi: "बैटरी", hinglish: "Battery", phase: 1 },
    { english: "Button", hindi: "बटन", hinglish: "Button", phase: 1 },
    { english: "Wire", hindi: "तार", hinglish: "Taar", phase: 1 },
    { english: "Plug", hindi: "प्लग", hinglish: "Plug", phase: 1 },
    { english: "Light", hindi: "रोशनी", hinglish: "Roshni", phase: 1 },
    { english: "Dark", hindi: "अंधेरा", hinglish: "Andhera", phase: 1 },
    { english: "Shadow", hindi: "परछाई", hinglish: "Parchaai", phase: 1 },
    { english: "Dust", hindi: "धूल", hinglish: "Dhool", phase: 1 },
    { english: "Mud", hindi: "कीचड़", hinglish: "Keechad", phase: 1 },
    { english: "Sand", hindi: "रेत", hinglish: "Ret", phase: 1 },
    { english: "Stone", hindi: "पत्थर", hinglish: "Patthar", phase: 1 },
    { english: "Wall", hindi: "दीवार", hinglish: "Deewar", phase: 1 },
    { english: "Floor", hindi: "फ़र्श", hinglish: "Farsh", phase: 1 },
    { english: "Roof", hindi: "छत", hinglish: "Chhat", phase: 1 },
    { english: "Stairs", hindi: "सीढ़ियां", hinglish: "Seedhiyan", phase: 1 },
    { english: "Key", hindi: "चाबी", hinglish: "Chaabi", phase: 1 },
    { english: "Lock", hindi: "ताला", hinglish: "Taala", phase: 1 },
    { english: "Mirror", hindi: "शीशा", hinglish: "Sheesha", phase: 1 },
    { english: "Comb", hindi: "कंघी", hinglish: "Kanghi", phase: 1 },
    { english: "Blanket", hindi: "कंबल", hinglish: "Kambal", phase: 1 },
    { english: "Pillow", hindi: "तकिया", hinglish: "Takiya", phase: 1 },
    { english: "Towel", hindi: "तौलिया", hinglish: "Tauliya", phase: 1 },
    { english: "Pocket", hindi: "जेब", hinglish: "Jeb", phase: 1 },
    { english: "Belt", hindi: "बेल्ट", hinglish: "Belt", phase: 1 },
    { english: "Wristwatch", hindi: "हाथ घड़ी", hinglish: "Haath ghadi", phase: 1 },
    { english: "Glasses", hindi: "चश्मा", hinglish: "Chashma", phase: 1 },
    { english: "Ring", hindi: "अंगूठी", hinglish: "Angoothi", phase: 1 },
    { english: "Line", hindi: "रेखा", hinglish: "Rekha", phase: 1 },
    { english: "Circle", hindi: "गोला", hinglish: "Gola", phase: 1 },
    { english: "Square", hindi: "चौकोर", hinglish: "Chaukor", phase: 1 },
    { english: "Shape", hindi: "आकार", hinglish: "Aakaar", phase: 1 },
    { english: "Measurement", hindi: "नाप", hinglish: "Naap", phase: 1 },
    { english: "Piece", hindi: "टुकड़ा", hinglish: "Tukda", phase: 1 },
    { english: "Good", hindi: "अच्छा", hinglish: "Acha", phase: 1 },
    { english: "Bad", hindi: "गंदा", hinglish: "Ganda", phase: 1 },
    { english: "Big", hindi: "बड़ा", hinglish: "Bada", phase: 1 },
    { english: "Small", hindi: "छोटा", hinglish: "Chota", phase: 1 },
    { english: "Hot", hindi: "गरम", hinglish: "Garam", phase: 1 },
    { english: "Cold", hindi: "ठंडा", hinglish: "Thanda", phase: 1 },
    { english: "Happy", hindi: "खुश", hinglish: "Khush", phase: 1 },
    { english: "Sad", hindi: "उदास", hinglish: "Udaas", phase: 1 },
    { english: "Fast", hindi: "जल्दी", hinglish: "Jaldi", phase: 1 },
    { english: "Slow", hindi: "धीरे", hinglish: "Dheere", phase: 1 },
    { english: "Here", hindi: "यहां", hinglish: "Yahan", phase: 1 },
    { english: "There", hindi: "वहां", hinglish: "Wahan", phase: 1 },
    { english: "More", hindi: "और", hinglish: "Aur", phase: 1 },
    { english: "Up", hindi: "ऊपर", hinglish: "Upar", phase: 1 },
    { english: "Down", hindi: "नीचे", hinglish: "Neeche", phase: 1 },
    { english: "Inside", hindi: "अंदर", hinglish: "Andar", phase: 1 },
    { english: "Outside", hindi: "बाहर", hinglish: "Bahar", phase: 1 },
    { english: "Right (Correct)", hindi: "सही", hinglish: "Sahi", phase: 1 },
    { english: "Wrong", hindi: "गलत", hinglish: "Galat", phase: 1 },
    { english: "Easy", hindi: "आसान", hinglish: "Aasan", phase: 1 },
    { english: "Hard", hindi: "मुश्किल", hinglish: "Mushkil", phase: 1 },
    { english: "Now", hindi: "अभी", hinglish: "Abhi", phase: 1 },
    { english: "Later", hindi: "बाद में", hinglish: "Baad mein", phase: 1 },
    { english: "New", hindi: "नया", hinglish: "Naya", phase: 1 },
    { english: "Old", hindi: "पुराना", hinglish: "Purana", phase: 1 },
    { english: "Dry", hindi: "सूखा", hinglish: "Sookha", phase: 1 },
    { english: "Full", hindi: "भरा", hinglish: "Bhara", phase: 1 },
    { english: "Empty", hindi: "खाली", hinglish: "Khaali", phase: 1 },
    { english: "Heavy", hindi: "भारी", hinglish: "Bhaari", phase: 1 },
    { english: "Light", hindi: "हल्का", hinglish: "Halka", phase: 1 },
    { english: "Today", hindi: "आज", hinglish: "Aaj", phase: 1 },
    { english: "Tomorrow", hindi: "कल", hinglish: "Kal", phase: 1 },
    { english: "Morning", hindi: "सुबह", hinglish: "Subah", phase: 1 },
    { english: "Evening", hindi: "शाम", hinglish: "Shaam", phase: 1 },
    { english: "Night", hindi: "रात", hinglish: "Raat", phase: 1 },
    { english: "Day", hindi: "दिन", hinglish: "Din", phase: 1 },
    { english: "Sweet", hindi: "मीठा", hinglish: "Meetha", phase: 1 },
    { english: "Spicy", hindi: "तीखा", hinglish: "Teekha", phase: 1 },
    { english: "Bitter", hindi: "कड़वा", hinglish: "Kadwa", phase: 1 },
    { english: "Sour", hindi: "खट्टा", hinglish: "Khatta", phase: 1 },
    { english: "Smart", hindi: "होशियार", hinglish: "Hoshiyaar", phase: 1 },
    { english: "Silly", hindi: "पागल", hinglish: "Pagal", phase: 1 },
    { english: "Brave", hindi: "बहादुर", hinglish: "Bahadur", phase: 1 },
    { english: "Scared", hindi: "डरा हुआ", hinglish: "Dara hua", phase: 1 },
    { english: "Angry", hindi: "गुस्सा", hinglish: "Gussa", phase: 1 },
    { english: "Funny", hindi: "मज़ाकिया", hinglish: "Mazakiya", phase: 1 },
    { english: "Strong", hindi: "ताकतवर", hinglish: "Takatwar", phase: 1 },
    { english: "Weak", hindi: "कमज़ोर", hinglish: "Kamzor", phase: 1 },
    { english: "Tall", hindi: "लंबा", hinglish: "Lamba", phase: 1 },
    { english: "Short", hindi: "नाटा", hinglish: "Naata", phase: 1 },
    { english: "Quiet", hindi: "शांत", hinglish: "Shaant", phase: 1 },
    { english: "Loud", hindi: "ज़ोर से", hinglish: "Zor se", phase: 1 },
    { english: "Half", hindi: "आधा", hinglish: "Aadha", phase: 1 },
    { english: "Right (Direction)", hindi: "दायें", hinglish: "Daayen", phase: 1 },
    { english: "Left", hindi: "बायें", hinglish: "Baayen", phase: 1 },
    { english: "Center", hindi: "बीच में", hinglish: "Beech mein", phase: 1 },
    { english: "Sick", hindi: "बीमार", hinglish: "Beemar", phase: 1 },
    { english: "Yes", hindi: "हां", hinglish: "Haan", phase: 1 },
    { english: "No", hindi: "नहीं", hinglish: "Nahi", phase: 1 },
    { english: "Hello", hindi: "नमस्ते", hinglish: "Namaste", phase: 1 },
    { english: "Bye", hindi: "अलविदा", hinglish: "Alvida", phase: 1 },
    { english: "Thanks", hindi: "शुक्रिया", hinglish: "Shukriya", phase: 1 },
    { english: "Sorry", hindi: "माफ़ करना", hinglish: "Maaf karna", phase: 1 },
    { english: "Please", hindi: "कृपया", hinglish: "Kripya", phase: 1 },
    { english: "What", hindi: "क्या", hinglish: "Kya", phase: 1 },
    { english: "Why", hindi: "क्यों", hinglish: "Kyun", phase: 1 },
    { english: "Where", hindi: "कहां", hinglish: "Kahan", phase: 1 },
    { english: "When", hindi: "कब", hinglish: "Kab", phase: 1 },
    { english: "Who", hindi: "कौन", hinglish: "Kaun", phase: 1 },
    { english: "How", hindi: "कैसे", hinglish: "Kaise", phase: 1 },
    { english: "Mine", hindi: "मेरा", hinglish: "Mera", phase: 1 },
    { english: "Yours", hindi: "तुम्हारा", hinglish: "Tumhara", phase: 1 },
    { english: "Help", hindi: "मदद", hinglish: "Madad", phase: 1 },
    { english: "Enough", hindi: "बस", hinglish: "Bas", phase: 1 },
    { english: "Family", hindi: "परिवार", hinglish: "Parivaar", phase: 1 },
    { english: "Bicycle", hindi: "साइकिल", hinglish: "Cycle", phase: 1 },
    { english: "Park", hindi: "पार्क", hinglish: "Park", phase: 1 },
    { english: "Always", hindi: "हमेशा", hinglish: "Hamesha", phase: 1 },
    { english: "Never", hindi: "कभी नहीं", hinglish: "Kabhi nahi", phase: 1 },

    // 🟡 PHASE 2: TWO-WORD COMBOS (116 Words)
    { english: "Come here", hindi: "यहां आओ", hinglish: "Yahan aao", phase: 2 },
    { english: "Go there", hindi: "वहां जाओ", hinglish: "Wahan jao", phase: 2 },
    { english: "Look here", hindi: "यहां देखो", hinglish: "Yahan dekho", phase: 2 },
    { english: "Drink water", hindi: "पानी पियो", hinglish: "Paani piyo", phase: 2 },
    { english: "Eat food", hindi: "खाना खाओ", hinglish: "Khana khao", phase: 2 },
    { english: "Give me", hindi: "मुझे दो", hinglish: "Mujhe do", phase: 2 },
    { english: "Take this", hindi: "यह लो", hinglish: "Yeh lo", phase: 2 },
    { english: "Good boy", hindi: "अच्छा लड़का", hinglish: "Acha ladka", phase: 2 },
    { english: "Get up", hindi: "उठ जाओ", hinglish: "Uth jao", phase: 2 },
    { english: "Sit down", hindi: "बैठ जाओ", hinglish: "Baith jao", phase: 2 },
    { english: "Don't do", hindi: "मत करो", hinglish: "Mat karo", phase: 2 },
    { english: "Do this", hindi: "यह करो", hinglish: "Yeh karo", phase: 2 },
    { english: "Read book", hindi: "किताब पढ़ो", hinglish: "Kitaab padho", phase: 2 },
    { english: "Play game", hindi: "गेम खेलो", hinglish: "Game khelo", phase: 2 },
    { english: "Wash hands", hindi: "हाथ धो", hinglish: "Haath dho", phase: 2 },
    { english: "Listen to me", hindi: "मेरी सुनो", hinglish: "Meri suno", phase: 2 },
    { english: "Tell me", hindi: "मुझे बताओ", hinglish: "Mujhe batao", phase: 2 },
    { english: "Go out", hindi: "बाहर जाओ", hinglish: "Bahar jao", phase: 2 },
    { english: "Come inside", hindi: "अंदर आओ", hinglish: "Andar aao", phase: 2 },
    { english: "Walk fast", hindi: "जल्दी चलो", hinglish: "Jaldi chalo", phase: 2 },
    { english: "Walk slow", hindi: "धीरे चलो", hinglish: "Dheere chalo", phase: 2 },
    { english: "Talk softly", hindi: "धीरे बोलो", hinglish: "Dheere bolo", phase: 2 },
    { english: "Stop crying", hindi: "रोना बंद करो", hinglish: "Rona band karo", phase: 2 },
    { english: "Very good", hindi: "बहुत अच्छा", hinglish: "Bahut acha", phase: 2 },
    { english: "Not this", hindi: "यह नहीं", hinglish: "Yeh nahi", phase: 2 },
    { english: "That one", hindi: "वह वाला", hinglish: "Woh wala", phase: 2 },
    { english: "Right now", hindi: "अभी तुरंत", hinglish: "Abhi turant", phase: 2 },
    { english: "Later on", hindi: "बाद में", hinglish: "Baad mein", phase: 2 },
    { english: "What happened", hindi: "क्या हुआ", hinglish: "Kya hua", phase: 2 },
    { english: "Let's go", hindi: "चलो चलें", hinglish: "Chalo chalein", phase: 2 },
    { english: "Very bad", hindi: "बहुत बुरा", hinglish: "Bahut bura", phase: 2 },
    { english: "Very big", hindi: "बहुत बड़ा", hinglish: "Bahut bada", phase: 2 },
    { english: "Come back", hindi: "वापस आओ", hinglish: "Wapas aao", phase: 2 },
    { english: "Give back", hindi: "वापस दो", hinglish: "Wapas do", phase: 2 },
    { english: "Move aside", hindi: "हट जाओ", hinglish: "Hat jao", phase: 2 },
    { english: "Stand up", hindi: "खड़े हो", hinglish: "Khade ho", phase: 2 },
    { english: "Hold this", hindi: "इसे पकड़ो", hinglish: "Ise pakdo", phase: 2 },
    { english: "Don't touch", hindi: "मत छुओ", hinglish: "Mat chhuo", phase: 2 },
    { english: "Be careful", hindi: "ध्यान से", hinglish: "Dhyan se", phase: 2 },
    { english: "Run fast", hindi: "तेज़ भागो", hinglish: "Tez bhago", phase: 2 },
    { english: "Jump high", hindi: "ऊपर कूदो", hinglish: "Upar kudo", phase: 2 },
    { english: "Sleep now", hindi: "अब सो जाओ", hinglish: "Ab so jao", phase: 2 },
    { english: "Wake up now", hindi: "अब उठ जाओ", hinglish: "Ab uth jao", phase: 2 },
    { english: "Wash face", hindi: "चेहरा धो", hinglish: "Chehra dho", phase: 2 },
    { english: "Brush teeth", hindi: "दांत साफ़ करो", hinglish: "Daant saaf karo", phase: 2 },
    { english: "Comb hair", hindi: "बाल बनाओ", hinglish: "Baal banao", phase: 2 },
    { english: "Take bath", hindi: "नहा लो", hinglish: "Naha lo", phase: 2 },
    { english: "Wear shirt", hindi: "शर्ट पहनो", hinglish: "Shirt pehno", phase: 2 },
    { english: "Hold my hand", hindi: "मेरा हाथ पकड़ो", hinglish: "Mera haath pakdo", phase: 2 },
    { english: "Give that", hindi: "वह दो", hinglish: "Woh do", phase: 2 },
    { english: "Come fast", hindi: "जल्दी आओ", hinglish: "Jaldi aao", phase: 2 },
    { english: "Eat slowly", hindi: "धीरे खाओ", hinglish: "Dheere khao", phase: 2 },
    { english: "Speak loud", hindi: "ज़ोर से बोलो", hinglish: "Zor se bolo", phase: 2 },
    { english: "Listen carefully", hindi: "ध्यान से सुनो", hinglish: "Dhyan se suno", phase: 2 },
    { english: "Look up", hindi: "ऊपर देखो", hinglish: "Upar dekho", phase: 2 },
    { english: "Look down", hindi: "नीचे देखो", hinglish: "Neeche dekho", phase: 2 },
    { english: "Go straight", hindi: "सीधे जाओ", hinglish: "Seedhe jao", phase: 2 },
    { english: "Turn back", hindi: "पीछे मुड़ो", hinglish: "Peeche mudo", phase: 2 },
    { english: "Stay here", hindi: "यहां रहो", hinglish: "Yahan raho", phase: 2 },
    { english: "Go away", hindi: "दूर जाओ", hinglish: "Door jao", phase: 2 },
    { english: "Wake him", hindi: "उसे उठाओ", hinglish: "Usse uthao", phase: 2 },
    { english: "Help me", hindi: "मदद करो", hinglish: "Madad karo", phase: 2 },
    { english: "Play outside", hindi: "बाहर खेलो", hinglish: "Bahar khelo", phase: 2 },
    { english: "Stay inside", hindi: "अंदर रहो", hinglish: "Andar raho", phase: 2 },
    { english: "Wash it", hindi: "इसे धो लो", hinglish: "Ise dho lo", phase: 2 },
    { english: "Clean it", hindi: "इसे साफ़ करो", hinglish: "Ise saaf karo", phase: 2 },
    { english: "Fix it", hindi: "इसे ठीक करो", hinglish: "Ise theek karo", phase: 2 },
    { english: "Throw it", hindi: "इसे फेंक दो", hinglish: "Ise phek do", phase: 2 },
    { english: "Catch it", hindi: "इसे पकड़ो", hinglish: "Ise pakdo", phase: 2 },
    { english: "Leave it", hindi: "छोड़ दो", hinglish: "Chhod do", phase: 2 },
    { english: "Start now", hindi: "अब शुरू करो", hinglish: "Ab shuru karo", phase: 2 },
    { english: "Stop now", hindi: "अब रुको", hinglish: "Ab ruko", phase: 2 },
    { english: "Very nice", hindi: "बहुत बढ़िया", hinglish: "Bahut badhiya", phase: 2 },
    { english: "Too bad", hindi: "बहुत खराब", hinglish: "Bahut kharab", phase: 2 },
    { english: "Don't fight", hindi: "लड़ो मत", hinglish: "Lado mat", phase: 2 },
    { english: "Don't cry", hindi: "रोओ मत", hinglish: "Roo mat", phase: 2 },
    { english: "Don't shout", hindi: "चिल्लाओ मत", hinglish: "Chillao mat", phase: 2 },
    { english: "Smile please", hindi: "मुस्कुराओ", hinglish: "Muskurao", phase: 2 },
    { english: "Say sorry", hindi: "सॉरी बोलो", hinglish: "Sorry bolo", phase: 2 },
    { english: "Thank you", hindi: "थैंक यू बोलो", hinglish: "Thank you bolo", phase: 2 },
    { english: "Turn it on", hindi: "चालू करो", hinglish: "Chalu karo", phase: 2 },
    { english: "Turn it off", hindi: "बंद करो", hinglish: "Band karo", phase: 2 },
    { english: "Volume up", hindi: "आवाज़ बढ़ाओ", hinglish: "Awaaz badao", phase: 2 },
    { english: "Volume down", hindi: "आवाज़ कम करो", hinglish: "Awaaz kam karo", phase: 2 },
    { english: "Charge it", hindi: "चार्ज करो", hinglish: "Charge karo", phase: 2 },
    { english: "Plug it in", hindi: "प्लग लगाओ", hinglish: "Plug lagao", phase: 2 },
    { english: "Search here", hindi: "यहां ढूंढो", hinglish: "Yahan dhoondo", phase: 2 },
    { english: "Click here", hindi: "यहां क्लिक करो", hinglish: "Yahan click karo", phase: 2 },
    { english: "Press this", hindi: "इसे दबाओ", hinglish: "Ise dabao", phase: 2 },
    { english: "Wait a minute", hindi: "एक मिनट रुको", hinglish: "Ek minute ruko", phase: 2 },
    { english: "Oh no", hindi: "ओह नहीं", hinglish: "Oh nahi", phase: 2 },
    { english: "Oh wow", hindi: "वाह", hinglish: "Wah", phase: 2 },
    { english: "It's awesome", hindi: "यह मस्त है", hinglish: "Yeh mast hai", phase: 2 },
    { english: "So boring", hindi: "बहुत बोरिंग", hinglish: "Bahut boring", phase: 2 },
    { english: "So funny", hindi: "बहुत फनी", hinglish: "Bahut funny", phase: 2 },
    { english: "So cute", hindi: "बहुत प्यारा", hinglish: "Bahut pyara", phase: 2 },
    { english: "Good job", hindi: "बढ़िया काम", hinglish: "Badhiya kaam", phase: 2 },
    { english: "Well done", hindi: "शाबाश", hinglish: "Shabaash", phase: 2 },
    { english: "Try again", hindi: "वापस कोशिश करो", hinglish: "Wapas koshish karo", phase: 2 },
    { english: "Don't push", hindi: "धक्का मत दो", hinglish: "Dhakka mat do", phase: 2 },
    { english: "Sit straight", hindi: "सीधे बैठो", hinglish: "Seedhe baitho", phase: 2 },
    { english: "Stand still", hindi: "चुपचाप खड़े रहो", hinglish: "Chupchap khade raho", phase: 2 },
    { english: "Walk safely", hindi: "आराम से चलो", hinglish: "Aaram se chalo", phase: 2 },
    { english: "Hold tight", hindi: "कस के पकड़ो", hinglish: "Kas ke pakdo", phase: 2 },
    { english: "Let go", hindi: "छोड़ दो", hinglish: "Chhod do", phase: 2 },
    { english: "Look ahead", hindi: "आगे देखो", hinglish: "Aage dekho", phase: 2 },
    { english: "Look back", hindi: "पीछे देखो", hinglish: "Peeche dekho", phase: 2 },
    { english: "Bring it", hindi: "इसे लाओ", hinglish: "Ise lao", phase: 2 },
    { english: "Keep it", hindi: "इसे रखो", hinglish: "Ise rakho", phase: 2 },
    { english: "Hide it", hindi: "इसे छुपाओ", hinglish: "Ise chupao", phase: 2 },
    { english: "Look carefully", hindi: "ध्यान से देखो", hinglish: "Dhyan se dekho", phase: 2 },
    { english: "Speak softly", hindi: "आराम से बोलो", hinglish: "Aaram se bolo", phase: 2 },
    { english: "Sit quietly", hindi: "शांति से बैठो", hinglish: "Shaanti se baitho", phase: 2 },
    { english: "Jump down", hindi: "नीचे कूदो", hinglish: "Neeche kudo", phase: 2 },
    { english: "Run back", hindi: "वापस भागो", hinglish: "Wapas bhago", phase: 2 },
    { english: "Carry this", hindi: "इसे उठाओ", hinglish: "Ise uthao", phase: 2 },

    // 🔴 PHASE 3: EVERYDAY SENTENCES (120 Words)
    { english: "I want water", hindi: "मुझे पानी चाहिए", hinglish: "Mujhe paani chahiye", phase: 3 },
    { english: "I am hungry", hindi: "मुझे भूख लगी है", hinglish: "Mujhe bhookh lagi hai", phase: 3 },
    { english: "I am thirsty", hindi: "मुझे प्यास लगी है", hinglish: "Mujhe pyaas lagi hai", phase: 3 },
    { english: "I am sleepy", hindi: "मुझे नींद आ रही है", hinglish: "Mujhe neend aa rahi hai", phase: 3 },
    { english: "I want to play", hindi: "मुझे खेलना है", hinglish: "Mujhe khelna hai", phase: 3 },
    { english: "Give it to me", hindi: "यह मुझे दो", hinglish: "Yeh mujhe do", phase: 3 },
    { english: "What is this?", hindi: "यह क्या है?", hinglish: "Yeh kya hai?", phase: 3 },
    { english: "Where are you?", hindi: "तुम कहां हो?", hinglish: "Tum kahan ho?", phase: 3 },
    { english: "Look at this", hindi: "इसको देखो", hinglish: "Isko dekho", phase: 3 },
    { english: "I don't know", hindi: "मुझे नहीं पता", hinglish: "Mujhe nahi pata", phase: 3 },
    { english: "I know", hindi: "मुझे पता है", hinglish: "Mujhe pata hai", phase: 3 },
    { english: "This is good", hindi: "यह अच्छा है", hinglish: "Yeh acha hai", phase: 3 },
    { english: "I am tired", hindi: "मैं थक गया हूँ", hinglish: "Main thak gaya hoon", phase: 3 },
    { english: "Let's play together", hindi: "चलो साथ खेलें", hinglish: "Chalo saath khelein", phase: 3 },
    { english: "Turn on the TV", hindi: "टीवी चालू करो", hinglish: "TV chalu karo", phase: 3 },
    { english: "Open the door", hindi: "दरवाज़ा खोलो", hinglish: "Darwaza kholo", phase: 3 },
    { english: "Close the window", hindi: "खिड़की बंद करो", hinglish: "Khidki band karo", phase: 3 },
    { english: "I like this", hindi: "मुझे यह पसंद है", hinglish: "Mujhe yeh pasand hai", phase: 3 },
    { english: "I don't like this", hindi: "मुझे यह पसंद नहीं है", hinglish: "Mujhe yeh pasand nahi hai", phase: 3 },
    { english: "Where is my toy?", hindi: "मेरा खिलौना कहां है?", hinglish: "Mera khilona kahan hai?", phase: 3 },
    { english: "Come with me", hindi: "मेरे साथ आओ", hinglish: "Mere saath aao", phase: 3 },
    { english: "Don't do this", hindi: "यह मत करो", hinglish: "Yeh mat karo", phase: 3 },
    { english: "Are you okay?", hindi: "तुम ठीक हो?", hinglish: "Tum theek ho?", phase: 3 },
    { english: "Go to sleep", hindi: "सोने जाओ", hinglish: "Sone jao", phase: 3 },
    { english: "Put on your shoes", hindi: "अपने जूते पहनो", hinglish: "Apne joote pehno", phase: 3 },
    { english: "Take off your clothes", hindi: "अपने कपड़े उतारो", hinglish: "Apne kapde utaro", phase: 3 },
    { english: "Wait for me", hindi: "मेरा इंतज़ार करो", hinglish: "Mera intezaar karo", phase: 3 },
    { english: "I am going", hindi: "मैं जा रहा हूँ", hinglish: "Main jaa raha hoon", phase: 3 },
    { english: "Listen to your dad", hindi: "पापा की बात सुनो", hinglish: "Papa ki baat suno", phase: 3 },
    { english: "This is for you", hindi: "यह तुम्हारे लिए है", hinglish: "Yeh tumhare liye hai", phase: 3 },
    { english: "My stomach is hurting", hindi: "मेरे पेट में दर्द है", hinglish: "Mere pet mein dard hai", phase: 3 },
    { english: "I am feeling cold", hindi: "मुझे ठंड लग रही है", hinglish: "Mujhe thand lag rahi hai", phase: 3 },
    { english: "I am feeling hot", hindi: "मुझे गर्मी लग रही है", hinglish: "Mujhe garmi lag rahi hai", phase: 3 },
    { english: "Can I go?", hindi: "क्या मैं जाऊं?", hinglish: "Kya main jau?", phase: 3 },
    { english: "Can I play?", hindi: "क्या मैं खेलूं?", hinglish: "Kya main khelu?", phase: 3 },
    { english: "Look at me", hindi: "मुझे देखो", hinglish: "Mujhe dekho", phase: 3 },
    { english: "Don't go there", hindi: "वहां मत जाओ", hinglish: "Wahan mat jao", phase: 3 },
    { english: "Come here quickly", hindi: "जल्दी यहां आओ", hinglish: "Jaldi yahan aao", phase: 3 },
    { english: "What are you doing?", hindi: "तुम क्या कर रहे हो?", hinglish: "Tum kya kar rahe ho?", phase: 3 },
    { english: "I want to eat", hindi: "मुझे खाना है", hinglish: "Mujhe khana hai", phase: 3 },
    { english: "I don't want this", hindi: "मुझे यह नहीं चाहिए", hinglish: "Mujhe yeh nahi chahiye", phase: 3 },
    { english: "Let me do it", hindi: "मुझे करने दो", hinglish: "Mujhe karne do", phase: 3 },
    { english: "It is very heavy", hindi: "यह बहुत भारी है", hinglish: "Yeh bahut bhaari hai", phase: 3 },
    { english: "Put it down", hindi: "इसे नीचे रखो", hinglish: "Ise neeche rakho", phase: 3 },
    { english: "Pick it up", hindi: "इसे उठाओ", hinglish: "Ise uthao", phase: 3 },
    { english: "Turn on the fan", hindi: "पंखे चालू करो", hinglish: "Pankha chalu karo", phase: 3 },
    { english: "Turn off the light", hindi: "लाइट बंद करो", hinglish: "Light band karo", phase: 3 },
    { english: "Give me my phone", hindi: "मुझे मेरा फ़ोन दो", hinglish: "Mujhe mera phone do", phase: 3 },
    { english: "Where is my bag?", hindi: "मेरा बैग कहां है?", hinglish: "Mera bag kahan hai?", phase: 3 },
    { english: "I will win", hindi: "मैं जीतूंगा", hinglish: "Main jeetunga", phase: 3 },
    { english: "You lost", hindi: "तुम हार गए", hinglish: "Tum haar gaye", phase: 3 },
    { english: "Let's go home", hindi: "चलो घर चलें", hinglish: "Chalo ghar chalein", phase: 3 },
    { english: "Who is there?", hindi: "वहां कौन है?", hinglish: "Wahan kaun hai?", phase: 3 },
    { english: "It is raining", hindi: "बारिश हो रही है", hinglish: "Baarish ho rahi hai", phase: 3 },
    { english: "The sun is out", hindi: "धूप निकली है", hinglish: "Dhoop nikli hai", phase: 3 },
    { english: "I love you", hindi: "मैं तुमसे प्यार करता हूँ", hinglish: "Main tumse pyar karta hoon", phase: 3 },
    { english: "See you tomorrow", hindi: "कल मिलेंगे", hinglish: "Kal milenge", phase: 3 },
    { english: "Good morning dad", hindi: "गुड मॉर्निंग पापा", hinglish: "Good morning Papa", phase: 3 },
    { english: "Good night mom", hindi: "गुड नाईट मम्मी", hinglish: "Good night Mummy", phase: 3 },
    { english: "Happy birthday", hindi: "जन्मदिन मुबारक", hinglish: "Janamdin mubarak", phase: 3 },
    { english: "What is your name?", hindi: "तुम्हारा नाम क्या है?", hinglish: "Tumhara naam kya hai?", phase: 3 },
    { english: "My name is...", hindi: "मेरा नाम... है", hinglish: "Mera naam... hai", phase: 3 },
    { english: "I am 8 years old", hindi: "मैं आठ साल का हूँ", hinglish: "Main aath saal ka hoon", phase: 3 },
    { english: "I have a toy", hindi: "मेरे पास खिलौना है", hinglish: "Mere paas khilona hai", phase: 3 },
    { english: "He is my friend", hindi: "वह मेरा दोस्त है", hinglish: "Woh mera dost hai", phase: 3 },
    { english: "Is this yours?", hindi: "क्या यह तुम्हारा है?", hinglish: "Kya yeh tumhara hai?", phase: 3 },
    { english: "Yes, it is mine", hindi: "हां, यह मेरा है", hinglish: "Haan, yeh mera hai", phase: 3 },
    { english: "No, it is not mine", hindi: "नहीं, यह मेरा नहीं है", hinglish: "Nahi, yeh mera nahi hai", phase: 3 },
    { english: "Show me your hand", hindi: "अपना हाथ दिखाओ", hinglish: "Apna haath dikhao", phase: 3 },
    { english: "You are a good boy", hindi: "तुम अच्छे लड़के हो", hinglish: "Tum ache ladke ho", phase: 3 },
    { english: "I want to build Legos", hindi: "मुझे लेगो बनाना है", hinglish: "Mujhe Lego banana hai", phase: 3 },
    { english: "This is my game", hindi: "यह मेरा गेम है", hinglish: "Yeh mera game hai", phase: 3 },
    { english: "Let me win", hindi: "मुझे जीतने दो", hinglish: "Mujhe jeetne do", phase: 3 },
    { english: "I am playing a game", hindi: "मैं गेम खेल रहा हूँ", hinglish: "Main game khel raha hoon", phase: 3 },
    { english: "Where is my remote?", hindi: "मेरा रिमोट कहां है?", hinglish: "Mera remote kahan hai?", phase: 3 },
    { english: "I don't want to sleep", hindi: "मुझे नहीं सोना है", hinglish: "Mujhe nahi sona hai", phase: 3 },
    { english: "I am not hungry", hindi: "मुझे भूख नहीं है", hinglish: "Mujhe bhookh nahi hai", phase: 3 },
    { english: "Can I watch TV?", hindi: "क्या मैं टीवी देख सकता हूँ?", hinglish: "Kya main TV dekh sakta hoon?", phase: 3 },
    { english: "What are we eating?", hindi: "हम क्या खा रहे हैं?", hinglish: "Hum kya kha rahe hain?", phase: 3 },
    { english: "I want ice cream", hindi: "मुझे आइसक्रीम चाहिए", hinglish: "Mujhe ice cream chahiye", phase: 3 },
    { english: "Let's go to the park", hindi: "चलो पार्क चलें", hinglish: "Chalo park chalein", phase: 3 },
    { english: "I am running fast", hindi: "मैं तेज़ भाग रहा हूँ", hinglish: "Main tez bhag raha hoon", phase: 3 },
    { english: "See what I made", hindi: "देखो मैंने क्या बनाया", hinglish: "Dekho maine kya banaya", phase: 3 },
    { english: "This is very cool", hindi: "यह बहुत मस्त है", hinglish: "Yeh bahut mast hai", phase: 3 },
    { english: "You are cheating", hindi: "तुम चीटिंग कर रहे हो", hinglish: "Tum cheating kar rahe ho", phase: 3 },
    { english: "It is my turn", hindi: "मेरी बारी है", hinglish: "Meri baari hai", phase: 3 },
    { english: "Give me five minutes", hindi: "मुझे पांच मिनट दो", hinglish: "Mujhe paanch minute do", phase: 3 },
    { english: "What is the time?", hindi: "टाइम क्या हुआ है?", hinglish: "Time kya hua hai?", phase: 3 },
    { english: "I have a headache", hindi: "मेरे सिर में दर्द है", hinglish: "Mere sir mein dard hai", phase: 3 },
    { english: "This is too hot", hindi: "यह बहुत गरम है", hinglish: "Yeh bahut garam hai", phase: 3 },
    { english: "Can you help me?", hindi: "क्या आप मेरी मदद कर सकते हो?", hinglish: "Kya aap meri madad kar sakte ho?", phase: 3 },
    { english: "Who is calling?", hindi: "कौन बुला रहा है?", hinglish: "Kaun bula raha hai?", phase: 3 },
    { english: "I am watching a movie", hindi: "मैं मूवी देख रहा हूँ", hinglish: "Main movie dekh raha hoon", phase: 3 },
    { english: "Don't touch my toys", hindi: "मेरे खिलौने मत छुओ", hinglish: "Mere khilone mat chhuo", phase: 3 },
    { english: "I want to go outside", hindi: "मुझे बाहर जाना है", hinglish: "Mujhe bahar jana hai", phase: 3 },
    { english: "Daddy is working", hindi: "पापा काम कर रहे हैं", hinglish: "Papa kaam kar rahe hain", phase: 3 },
    { english: "Mommy is sleeping", hindi: "मम्मी सो रही हैं", hinglish: "Mummy so rahi hain", phase: 3 },
    { english: "Are we going out?", hindi: "क्या हम बाहर जा रहे हैं?", hinglish: "Kya hum bahar jaa rahe hain?", phase: 3 },
    { english: "I had a lot of fun", hindi: "मुझे बहुत मज़ा आया", hinglish: "Mujhe bahut maza aaya", phase: 3 },
    { english: "Let's do it again", hindi: "चलो दोबारा करते हैं", hinglish: "Chalo dobara karte hain", phase: 3 },
    { english: "My battery is low", hindi: "मेरी बैटरी लो है", hinglish: "Meri battery low hai", phase: 3 },
    { english: "Can I use your phone?", hindi: "क्या मैं आपका फ़ोन यूज़ कर सकता हूँ?", hinglish: "Kya main aapka phone use kar sakta hoon?", phase: 3 },
    { english: "What is the password?", hindi: "पासवर्ड क्या है?", hinglish: "Password kya hai?", phase: 3 },
    { english: "I lost my toy", hindi: "मेरा खिलौना गुम गया", hinglish: "Mera khilona ghum gaya", phase: 3 },
    { english: "I found it", hindi: "मुझे मिल गया", hinglish: "Mujhe mil gaya", phase: 3 },
    { english: "The food is tasty", hindi: "खाना टेस्टी है", hinglish: "Khana tasty hai", phase: 3 },
    { english: "I need more food", hindi: "मुझे और खाना चाहिए", hinglish: "Mujhe aur khana chahiye", phase: 3 },
    { english: "I am full", hindi: "मेरा पेट भर गया", hinglish: "Mera pet bhar gaya", phase: 3 },
    { english: "Can we buy this?", hindi: "क्या हम यह खरीद सकते हैं?", hinglish: "Kya hum yeh khareed sakte hain?", phase: 3 },
    { english: "I don't have money", hindi: "मेरे पास पैसे नहीं हैं", hinglish: "Mere paas paise nahi hain", phase: 3 },
    { english: "You are my best friend", hindi: "तुम मेरे बेस्ट फ्रेंड हो", hinglish: "Tum mere best friend ho", phase: 3 },
    { english: "Let's make a house", hindi: "चलो घर बनाते हैं", hinglish: "Chalo ghar banate hain", phase: 3 },
    { english: "I am scared of the dark", hindi: "मुझे अंधेरे से डर लगता है", hinglish: "Mujhe andhere se darr lagta hai", phase: 3 },
    { english: "Turn on the light please", hindi: "कृपया लाइट चालू कर दो", hinglish: "Kripya light chalu kardo", phase: 3 },
    { english: "Where are my clothes?", hindi: "मेरे कपड़े कहां हैं?", hinglish: "Mere kapde kahan hain?", phase: 3 },
    { english: "The water is cold", hindi: "पानी ठंडा है", hinglish: "Paani thanda hai", phase: 3 },
    { english: "I am sweating", hindi: "मुझे पसीना आ रहा है", hinglish: "Mujhe paseena aa raha hai", phase: 3 },
    { english: "Wipe your face", hindi: "अपना चेहरा पोंछो", hinglish: "Apna chehra pocho", phase: 3 },
    { english: "Blow your nose", hindi: "अपनी नाक साफ़ करो", hinglish: "Apni naak saaf karo", phase: 3 },
    { english: "Wash your feet", hindi: "अपने पैर धो", hinglish: "Apne paer dho", phase: 3 },
    { english: "Tie your shoelaces", hindi: "अपने जूते बांधो", hinglish: "Apne joote baandho", phase: 3 },
    { english: "Pack your bag", hindi: "अपना बैग पैक करो", hinglish: "Apna bag pack karo", phase: 3 },
    { english: "It is time for school", hindi: "स्कूल का टाइम हो गया", hinglish: "School ka time ho gaya", phase: 3 },
    { english: "See you later", hindi: "बाद में मिलेंगे", hinglish: "Baad mein milenge", phase: 3 },
    { english: "Drive the car", hindi: "गाड़ी चलाओ", hinglish: "Gaadi chalao", phase: 3 },
    { english: "We are going to the mall", hindi: "हम मॉल जा रहे हैं", hinglish: "Hum mall jaa rahe hain", phase: 3 },
    { english: "Did you finish it?", hindi: "क्या तुमने खत्म किया?", hinglish: "Kya tumne khatam kiya?", phase: 3 },
    { english: "Yes, I am done", hindi: "हां, मेरा हो गया", hinglish: "Haan, mera ho gaya", phase: 3 },
    { english: "No, I need time", hindi: "नहीं, मुझे टाइम चाहिए", hinglish: "Nahi, mujhe time chahiye", phase: 3 },
    { english: "Tell me a story", hindi: "मुझे एक कहानी सुनाओ", hinglish: "Mujhe ek kahani sunao", phase: 3 },
    { english: "It is a beautiful day", hindi: "आज बहुत अच्छा दिन है", hinglish: "Aaj bahut acha din hai", phase: 3 },
    { english: "I am bored", hindi: "मैं बोर हो रहा हूँ", hinglish: "Main bore ho raha hoon", phase: 3 },
    { english: "Let's read a book", hindi: "चलो किताब पढ़ते हैं", hinglish: "Chalo kitaab padhte hain", phase: 3 },
    { english: "Can we go now?", hindi: "क्या हम अब जा सकते हैं?", hinglish: "Kya hum ab jaa sakte hain?", phase: 3 },
    { english: "I did it!", hindi: "मैंने कर लिया!", hinglish: "Maine kar liya!", phase: 3 },
    { english: "Where is mom?", hindi: "मम्मी कहाँ हैं?", hinglish: "Mummy kahan hain?", phase: 3 },
    { english: "Where is dad?", hindi: "पापा कहाँ हैं?", hinglish: "Papa kahan hain?", phase: 3 }
];